linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - gosimple
    - ineffassign
    - revive
    - unused

linters-settings:
  revive:
    severity: warning
  staticcheck:
    checks: ["-SA1027"]  # Отключаем SA1027

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  allow-parallel-runners: false
